name: CI/CD Pipeline

# Déclenchement du workflow via repository_dispatch (venant du dépôt privé)
on:
  repository_dispatch:
    types: [deploy]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt privé
      - name: Checkout code from the private repository
        uses: actions/checkout@v3
        with:
          repository: mnassrib/lettercraft-backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      # Étape 2 : Configurer l'environnement Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Étape 3 : Installer les dépendances du projet
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings

      # Étape 5 : Créer une image Docker seulement si les tests réussissent
      - name: Build Docker image
        if: success()
        run: |
          docker build -t lettercraft .

      # Étape 6 : Déployer sur Render seulement si la création de l'image Docker a réussi
      - name: Deploy to Render
        if: success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}  \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            -H 'Accept: application/json' \
            -d ''
          
      # Optionnel : Notifier de la réussite du déploiement
      - name: Notify deployment success
        run: echo "Deployment to Render was successful!"
