name: CI/CD Pipeline from Private Repo

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Cloner le dépôt privé
    - name: Checkout private Flask repository
      uses: actions/checkout@v3
      with:
        repository: mnassrib/lettercraft-backend
        token: ${{ secrets.GH_PAT }}

    # 2. Configurer Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Exécuter les tests
    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings

    # 5. Déploiement sur Render
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }} \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
        -H 'Accept: application/json' \
        --data '{"clearCache":false}'
